#!/bin/bash
# ESO zram swap: PERCENT of RAM as zstd-compressed swap (settings in /etc/default/zramswap, same file as ESO 3.x)
ALGO=zstd PERCENT=60 PRIORITY=100
[[ -r /etc/default/zramswap ]] && . /etc/default/zramswap
case $1 in
start)
    modprobe zram num_devices=1 2>/dev/null || true
    [[ -e /dev/zram0 ]] || exit 0
    kb=$(awk '/MemTotal/{print $2}' /proc/meminfo)
    zramctl /dev/zram0 --algorithm "$ALGO" --size "$((kb * PERCENT / 100))KiB" 2>/dev/null \
        || zramctl /dev/zram0 --algorithm lzo-rle --size "$((kb * PERCENT / 100))KiB"
    mkswap -q /dev/zram0 && swapon -p "$PRIORITY" /dev/zram0 ;;
stop)
    swapoff /dev/zram0 2>/dev/null; zramctl --reset /dev/zram0 2>/dev/null; true ;;
esac
